from enum import auto

class AreaUiType():
    VIEW_3D = auto()
    IMAGE_EDITOR = auto()
    UV = auto()
    CompositorNodeTree = auto()
    TextureNodeTree = auto()
    GeometryNodeTree = auto()
    ShaderNodeTree = auto()
    SEQUENCE_EDITOR = auto()
    CLIP_EDITOR = auto()
    DOPESHEET = auto()
    TIMELINE = auto()
    FCURVES = auto()
    DRIVERS = auto()
    NLA_EDITOR = auto()
    TEXT_EDITOR = auto()
    CONSOLE = auto()
    INFO = auto()
    OUTLINER = auto()
    PROPERTIES = auto()
    FILES = auto()
    ASSETS = auto()
    SPREADSHEET = auto()
    PREFERENCES = auto()