from enum import auto

class AreaType():
    EMPTY = auto()
    VIEW_3D = auto()
    UV = auto()
    IMAGE_EDITOR = auto()
    NODE_EDITOR = auto()
    SEQUENCE_EDITOR = auto()
    CLIP_EDITOR = auto()
    DOPESHEET_EDITOR = auto()
    GRAPH_EDITOR = auto()
    NLA_EDITOR = auto()
    TEXT_EDITOR = auto()
    CONSOLE = auto()
    INFO = auto()
    TOPBAR = auto()
    STATUSBAR = auto()
    OUTLINER = auto()
    PROPERTIES = auto()
    FILE_BROWSER = auto()
    SPREADSHEET = auto()
    PREFERENCES = auto()